### ISSUE TITLE
Cannot read property 'title' of undefined

### ISSUE THREAD

**Issue by agauniyal** [agauniyal/vscode-caniuse#1]
> It very good idea so I rate 4. But it won't work for me, when I highlight something and push "alt+i" I just get error message "Cannon read property 'title' of undefined". In the same time in status bar I see only "Search in browser". I hope it will fixed someday.

**Comment by agauniyal** [comment]
This might happen when you're highlighting and searching for something that isn't in the can-i-use database. I'll look more into it.

**Comment by agauniyal** [comment]
I've made changes to error handling which displays better error messages on failure so you can update to latest version. Feel free to reopen if issue persists.

**Comment by Endlessmist** [comment]
Thank you for your reply!

OS: Windows 10 64bit
VSCode: v,1.9.1

I tried to searching and highlighting many words from my CSS. But some of it was just regular CSS rules, like "box-sizing" or "display" - both give error. Now I installed new version and tried "transform-origin" - same situation. Next one is value of transform property - "translate", not sure that it should work with values too, but to give you more info I just write what I did. On caniuse site i tried to find "translate" and found correct results.

And now error message more clear so is "Cannot find property in local database, you can still search through status bar."

And at last one little thing - maybe is better to make titles of property groups more similar with caniuse site? I mean when I highlight "width" it shows me "img-naturalwidth-naturalheight" but on site is "natural width & natural height image property" and so on. When someone use caniuse website before maybe he try to catch by eyes familiar words and titles, it intuitive. So if all titles will copy titles from site maybe it will easier to recognize what you need. Sorry for post this in another issue.

**Comment by agauniyal** [comment]
@Endlessmist This plugin simply mirrors the calls between caniuse data and your search query. I understand what you're trying to say, `color` should also show `background-color` as property and some css properties are not even available to query for, but that's because caniuse doesn't provide them. So unfortunately this isn't available now but I'll definitely put this into my todo list and as soon as I get time I'll make sure to implement them 😄 .
